AWSTemplateFormatVersion: "2010-09-09"

Description: -<
    secrets-rotation-service

Transform: [
    "AWS::Serverless-2016-10-31"
]

Globals: { Function: { Runtime: "nodejs14.x", Timeout: 30, Architectures: [ "x86_64" ] } }

Resources:
    Function: # --> List All Secrets, Administrative
        Type: AWS::Serverless::Function
        Properties:
            Description: "List All Secrets, Sanitized, Administrative"
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            MemorySize: 128
            Events: { API: {
                Type: "Api",
                Properties: {
                    Path: "/api/secrets/administration",
                    Method: "GET"
                }
            } }

Outputs:
    Endpoint:
        Description: "API Gateway URL"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"